angular.module('mainApp').factory('people', function people() {

  return [    
    {name: 'Adam Brody'},
    {name: 'Adam Lambert'},
    {name: 'Adam Levine'},
    {name: 'Adam Sandler'},
    {name: 'Adrien Brody'},
    {name: 'Albert Einstein'},
    {name: 'Alicia Silverstone'},
    {name: 'Alona Tal'},
    {name: 'Amanda Peet'},
    {name: 'Amy Winehouse'},
    {name: 'Andrew Garfield'},
    {name: 'Andy Kaufman'},
    {name: 'Anton Yelchin'},
    {name: 'Arthur Miller'},
    {name: 'Asaf Avidan'},
    {name: 'Ayelet Zurer'},
    {name: 'Bar Paly'},
    {name: 'Bar Refaeli'},
    {name: 'Barbra Streisand'},
    {name: 'Baruch Spinoza'},
    {name: 'Ben and Jerry', wiki: 'Ben_%26_Jerry%27s'},        
    {name: 'Ben Barnes', wiki: 'Ben_Barnes_(actor)'},
    {name: 'Ben Feldman', wiki: 'Ben_Feldman_(actor)'},
    {name: 'Ben Stiller'},
    {name: 'Benjamin Disraeli'},       
    {name: 'Billy Crystal'},
    {name: 'Billy Joel'},
    {name: 'Bob Dylan'},
    {name: 'Bob Marley', score: 1},
    {name: 'Bob Saget'},
    {name: 'Brooke Burke'},
    {name: 'Bruno Mars', score: 1},
    {name: 'Carole King'},
    {name: 'Carrie Fisher', score: 2},        
    {name: 'Chris Pine', score: 1},
    {name: 'Coen Brothers'}, 
    {name: 'Daniel Day-Lewis'},
    {name: 'Daniel Radcliffe'},
    {name: 'Dave Franco'},
    {name: 'David Beckham', score: 2},
    {name: 'David Blaine', score: 2},
    {name: 'David Copperfield', wiki: 'David_Copperfield_(illusionist)'},
    {name: 'David Duchovny', score: 2},
    {name: 'David Schwimmer'},
    {name: 'Daryl Hannah', score: 2},
    {name: 'Dianna Agron'},
    {name: 'Drake', wiki: 'Drake_(musician)'},
    {name: 'Dustin Hoffman'},
    {name: 'Elizabeth Banks'},    
    {name: 'Elizabeth Berkley'},    
    {name: 'Elizabeth Taylor'},
    {name: 'Emile Berliner'},
    {name: 'Emmy Rossum'},
    {name: 'Enrique Iglesias', score: 1},
    {name: 'Eva Green'},
    {name: 'Evan Rachel Wood'},
    {name: 'Franz Kafka'},
    {name: 'Fred Savage'},
    {name: 'Gal Gadot'},
    {name: 'Garry Kasparov', score: 2},
    {name: 'Gene Wilder'},
    {name: 'Gina Gershon'},
    {name: 'Gustav Mahler', score: 2},
    {name: 'Gwyneth Paltrow'},
    {name: 'Hank Azaria'},
    {name: 'Hans Zimmer'},
    {name: 'Harrison Ford'},
    {name: 'Harry Houdini'},
    {name: 'Harvey Keitel'},
    {name: 'Heinrich Heine', score: 2},
    {name: 'Helen Hunt', score: 1},
    {name: 'Henry Winkler'},
    {name: 'H. J. Muller', wiki: 'Hermann_Joseph_Muller'},
    {name: 'Isaac Asimov'},        
    {name: 'Isla Fisher'},
    {name: 'J. D. Salinger'},
    {name: 'J. J. Abrams'},
    {name: 'JC Van Damme', wiki: 'Jean-Claude_Van_Damme', score: 1},
    {name: 'Jack Black'},
    {name: 'Jake Gyllenhaal'},                   
    {name: 'James Franco'},
    {name: 'Jason Alexander'},
    {name: 'Jason Segel'},
    {name: 'Jeff Goldblum'},
    {name: 'Jennifer Connelly'},
    {name: 'Jerry Bruckheimer'},
    {name: 'Jerry Seinfeld'},
    {name: 'Jessica Alba', score: 1},
    {name: 'Jessica Biel', score: 1},
    {name: 'Jesse Eisenberg'},
    {name: 'Jesus'},
    {name: 'John von Neumann', score: 2},
    {name: 'Joaquin Phoenix'},
    {name: 'Jon Stewart'},
    {name: 'Jonas Salk'},
    {name: 'Joseph Gordon-Levitt'},
    {name: 'Julia Louis-Dreyfus', score: 1},
    {name: 'Julianna Margulies'},
    {name: 'Julianne Moore', score: 1},
    {name: 'Karl Marx'},
    {name: 'Kat Dennings'},
    {name: 'Kate Hudson'},
    {name: 'Kirk Douglas'},
    {name: 'Larry David'},    
    {name: 'Larry King'},
    {name: 'Larry Page'},
    {name: 'Lars Ulrich', score: 1},
    {name: 'Lauren Cohan'},
    {name: 'Lenny Kravitz', score: 2},
    {name: 'Leon Trotsky'},           
    {name: 'Leonard Cohen'},
    {name: 'Leonard Nimoy'},
    {name: 'Levi Strauss'},
    {name: 'Liev Schreiber'},
    {name: 'Lisa Bonet'},
    {name: 'Lisa Kudrow'},
    {name: 'Lou Reed'},
    {name: 'Louis C.K.', score: 1},
    {name: 'Mandy Patinkin'},
    {name: 'Marc Chagall'},            
    {name: 'Marcel Marceau'},
    {name: 'Marcel Proust'},
    {name: 'Marilyn Monroe'},
    {name: 'Mark Ivanir'},
    {name: 'Mark Knopfler', score: 2},
    {name: 'Mark-Paul Gosselaar', score: 1},
    {name: 'Mark Zuckerberg'},
    {name: 'Marx Brothers'},
    {name: 'Matisyahu'},
    {name: 'Matthew Broderick'},
    {name: 'Mel Brooks'},
    {name: 'Melanie Laurent', wiki: 'M%C3%A9lanie_Laurent'},
    {name: 'Michael Douglas', score: 2},    
    {name: 'Mila Kunis'},
    {name: 'Mili Avital'},
    {name: 'Natalie Portman'},
    {name: 'Neve Campbell', score: 2},
    {name: 'Niels Bohr'},
    {name: 'Nikki Reed'},
    {name: 'Noah Wyle', score: 2},
    {name: 'Nora Arnezeder'},
    {name: 'Olivia Wilde', score: 1},
    {name: 'Oscar Isaac', score: 1},
    {name: 'Patricia Arquette'},
    {name: 'Paul Auster'},
    {name: 'Paul Ehrlich'},
    {name: 'Paul Erdos', wiki: 'Paul_Erd%C5%91s'},
    {name: 'Paul Newman'},
    {name: 'Paul Rudd'},
    {name: 'Paula Abdul'},
    {name: 'Peter Falk'},
    {name: 'Pink', wiki: 'Pink_(singer)'},
    {name: 'Rachel Weisz'},
    {name: 'Ray Kurzweil'},
    {name: 'Richard Dreyfuss'},
    {name: 'Richard Feynman'},
    {name: 'River Phoenix'},
    {name: 'Robert Downey Jr.',score: 2},
    {name: 'Rube Goldberg'},
    {name: 'Sacha Baron Cohen'},
    {name: 'Sarah Jessica Parker'},    
    {name: 'Sarah Michelle Gellar'},    
    {name: 'Sarah Silverman'},           
    {name: 'Scarlett Johansson'},
    {name: 'Sean Penn', score: 2},
    {name: 'Selma Blair'},
    {name: 'Sergey Brin'},
    {name: 'Seth Green'},
    {name: 'Seth Rogen'},
    {name: 'Sigmund Freud'},
    {name: 'Simon and Garfunkel', wiki: 'Simon_%26_Garfunkel'},
    {name: 'Stanley Kubrick'},
    {name: 'Steve Guttenberg'},
    {name: 'Steven Spielberg'},
    {name: 'Sylvester Stallone', score: 1},
    {name: 'Vladimir Lenin', score: 1},  
    {name: 'William Shatner'},
    {name: 'Winona Ryder'},            
    {name: 'Woody Allen'},
    {name: 'Zac Efron'}
  ]

});
